### ISSUE TITLE
Authentication failure when trying to run the sync_salesforce command

### ISSUE THREAD

**Issue by natea** [edx/edx-salesforce#14]
### Description

I'm trying to run the sync command, but it's reporting `LookupError: oauth failed: developer@appsembler.com: {"error":"invalid_grant","error_description":"authentication failure"}`

I've checked the username, password, consumer key and secret and they all look correct. I read in the django-salesforce issue tracker that you need to append your token to the password unless you've whitelisted your IP address in Security->Network Access. I whitelisted my IP, but I'm still getting this error.

Do you know where I can find this token?

```
$ python manage.py sync_salesforce -s localhost -o example.com --settings=settings.local
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/Users/nateaune/Documents/code/hawthorn/edx-salesforce/edx_salesforce/management/commands/sync_salesforce.py", line 45, in __init__
    self.pricebook = Pricebook2.objects.get(is_standard=True)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/backend/manager.py", line 30, in get_queryset
    if not router.is_sf_database(self.db):
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/router.py", line 27, in is_sf_database
    engine = connections[db].settings_dict['ENGINE']
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/django/db/utils.py", line 212, in __getitem__
    conn = backend.DatabaseWrapper(db, alias)
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/backend/base.py", line 114, in __init__
    self.make_session()
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/backend/base.py", line 124, in make_session
    sf_instance_url = sf_session.auth.instance_url
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/auth.py", line 144, in instance_url
    return self.get_auth()['instance_url']
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/auth.py", line 118, in get_auth
    oauth_data[db_alias] = self.authenticate()
  File "/Users/nateaune/.virtualenvs/edxsalesforce/lib/python2.7/site-packages/salesforce/auth.py", line 198, in authenticate
    raise LookupError("oauth failed: %s: %s" % (settings_dict['USER'], response.text))
LookupError: oauth failed: developer@appsembler.com: {"error":"invalid_grant","error_description":"authentication failure"}
```

**Comment by douglashall** [comment]
Hi Nate!

I found this: https://success.salesforce.com/answers?id=90630000000glADAAY

Are you able to successfully make a Salesforce API request with `curl`?

**Comment by natea** [comment]
yes, i went here and was able to reset my security token: 
https://na85.lightning.force.com/lightning/settings/personal/ResetApiToken/home
But even after appending it to my password, I'm still getting that error
message:LookupError: oauth failed: developer@appsembler.com:
{"error":"invalid_grant","error_description":"authentication failure"}  





On Sat, Nov 10, 2018 1:35 PM, Douglas Hall notifications@github.com  wrote:
Hi Nate!

I found this: https://success.salesforce.com/answers?id=90630000000glADAAY

Are you able to successfully make a Salesforce API request with curl?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.





Website:http://www.appsembler.comBlog: http://www.appsembler.com/blogTwitter:
http://twitter.com/nateaLinkedIn:http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by natea** [comment]
Ok, I found out where to get the Security Token, but even after appending it to my password, I'm still getting the same error. Any other ideas?
